source ~/dotfiles/shell/colours.sh
source ~/dotfiles/shell/environment.sh
source ~/dotfiles/shell/commands.sh
source ~/dotfiles/shell/completions.sh

# Homebrew bash completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
	. `brew --prefix`/etc/bash_completion
fi

# pip completion
eval "`pip completion --bash`"

PS1="\[\033[0;1;32m\]\u@\h:\[\033[0;1;34m\]\w\[\033[0;1;33m\]\$ \[\033[0m\]"
