set guifont=Monaco:h15.00
set columns=80
set lines=25
colorscheme koehler
set bg=dark
if &background == "dark"
	hi normal guibg=black
	"set transp=8
	set transp=15
endif
set guioptions-=T

" No idea why this won't come over from ~/.vimrc (did try)...
au BufNewFile,BufRead *.py set tabstop=4 softtabstop=4
